### ISSUE TITLE
Non hai documentación.

### ISSUE THREAD

**Issue by lauramcastro** [andy135/PracticaVVS#4]
O proxecto non inclúe documentación: non hai comentarios en JavaDoc no código fonte, e tampouco hai ningún diagrama UML que represente a estrutura actual da implementación (a evolución do diagrama do enunciado).

**Comment by andy135** [comment]
Hola profe @lauramcastro, qué documentación hace falta además de un diagrama de clases que represente el código implementado?

**Comment by lauramcastro** [comment]
En esta "iteración" (segunda semana de trabajo) lo exigible a cualquier equipo es que tenga por lo menos un diagrama de clases UML de todo el sistema y documentación generable en Javadoc, es decir, el código fuente anotado convenientemente de manera que al generar el Javadoc cada clase implementada y sus métodos estén apropiadamente comentados.
