### ISSUE TITLE
Método buscar() en cancion y anuncio

### ISSUE THREAD

**Issue by angelcastro2** [andy135/PracticaVVS#5]
El método buscar, busca en el titulo y  tiene que devolver una estructura de datos con la cancion/anuncio si es que la cancion/anuncio tiene un titulo que concuerde con la busqueda.

**Comment by lauramcastro** [comment]
Por qué está pechado este bug se a implementación de buscar en Canción e Anuncio aínda devolve "null"?

**Comment by angelcastro2** [comment]
De hecho, os hemos hecho una pull request, solo teneis que aceptarla y ya os soluciona eso.
