### ISSUE TITLE
Tokens

### ISSUE THREAD

**Issue by pedrofl** [andy135/PracticaVVS#6]
No se propaga los tokens en los servidores de respaldo. Además, si un token es nulo o si no le queda usos, generas un token nuevo.

**Comment by iagocanalejas** [comment]
En ningun lugar se dice que los tokens deban propagarse, los servidores siempre tienen acceso a sus servidores de respaldo, los servidores usan el atributo respaldoToken para tener siempre acceso a sus servidores respaldados.
En ningun lado se genera un token nuevo en el caso de que este sea null o no le queden usos eso solo se hace para los tokens de servidores

**Comment by pedrofl** [comment]
En el servidor de respaldo:
if(respaldoToken==null||respaldoToken.getCount()==0){
                respaldoToken = respaldo.alta();
}
Entonces si al servidor de respaldo le pasas un token null o sin usos, creas un token nuevo, en vez de generar una lista con contenidos y anuncios intercalados.

Si haces una búsqueda en un servidor con respaldo, entiendo que usas un token en el padre, y si este no tiene contenidos, haces una búsqueda en el servidor que respalda al servidor principal con el mismo token.

**Comment by iagocanalejas** [comment]
Vale aunque no es exactamente como me indicaste tienes razon y ese error existe y ya esta solucionado.
