### ISSUE TITLE
Error método buscar() en servidor simple

### ISSUE THREAD

**Issue by avelinorios** [andy135/PracticaVVS#7]
En el primer if que os copio aquí abajo, metéis todos los contenidos en la lista y a continuación si el token está a cero concatenáis todos los anuncios en la lista, quedando todos los contenidos al principio y todos los anuncios al final. 
Cada vez que se añade un contenido a la lista se debería decrementar el valor del token.
            for (Contenido c : Contenidos) { // Buscamos el contenido deseado
                if (c.obtenerTitulo().contains(subcadena)) {
                    list.add(c);
                }
            }
            if (token.getCount() <= 0) {// Anadimos publicidad de ser necesario
                for (int i = 0; i < list.size(); i += 3) {
                    if (i < list.size()) {
                        list.add(new Anuncio());
                    }
                }
            }

**Comment by iagocanalejas** [comment]
Ya arreglamos el problema al concatenar los anuncios, en cuanto a decrementar el token decidimos que cada busqueda cuente como 1 gasto de token devuelva los elementos que devuelva
